# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-18 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=50)),
                ('pathname', models.FileField(upload_to='upload/')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
