# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_uploadinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
            ],
        ),
    ]
